// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace BabysitterKata
{
	public class Babysitter
	{

		public int SetStartTime(int inputTime)
		{
			if(inputTime < 1700)
				return -1;

			return 1800;
		}

		public int SetEndTime(int inputTime)
		{
			if(inputTime > 0400)
				return -1;

			return 0300;
		}

		public int SetBedTime(int inputTime)
		{
			return 2000;
		}
	}
}

