// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace BabysitterKata
{
	public class Babysitter
	{
		private int startTime;
		private int endTime;
		private int bedTime;

		public int SetStartTime(int inputTime)
		{
			if(inputTime >= 0 && inputTime <= 0400)
				inputTime += 2400;

			if(inputTime < 1700)
				return -1;

			startTime = inputTime;
			return inputTime;
		}

		public int SetEndTime(int inputTime)
		{
			if(inputTime >= 0 && inputTime <= 0400)
				inputTime += 2400;

			if(inputTime < startTime || inputTime > 2800 || (inputTime > 0400 && inputTime < 1700))
				return -1;

			endTime = inputTime;
			return inputTime;
		}

		public int SetBedTime(int inputTime)
		{
			if(inputTime >= 0 && inputTime <= 0400)
				inputTime += 2400;

			if(inputTime > endTime || inputTime < startTime)
				return -1;

			bedTime = inputTime;
			return inputTime;
		}

		public int CalculatePay()
		{
			if(startTime == endTime)
				return 0;

			int startToBedTimeHours = startTime < 2400 ? (bedTime - startTime) / 100 : 0;
			int bedTimeToMidnightHours = endTime < 2400 ? (endTime - bedTime) / 100 : (2400 - bedTime) / 100;
			int midnightToEndOfJobHours = startTime > 2400 ? (endTime - startTime) / 100 : (endTime - 2400) / 100;

			if(startToBedTimeHours < 0)
				startToBedTimeHours = 0;
			if(bedTimeToMidnightHours < 0)
				bedTimeToMidnightHours = 0;
			if(midnightToEndOfJobHours < 0)
				midnightToEndOfJobHours = 0;

			return startToBedTimeHours * 12 + bedTimeToMidnightHours * 8 + midnightToEndOfJobHours * 16;
		}
	}
}

