// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using NUnit.Framework;

namespace BabysitterKata
{
	[TestFixture()]
	public class BabysitterTest
	{
		Babysitter b;

		[SetUp] public void Init()
		{
			b = new Babysitter();
		}

		[TearDown] public void Dispose()
		{
			b = null;
		}

		[Test()]
		public void whenBabysitterIsPassedAValidStartTimeItReturnsTheGivenTime ()
		{
			Assert.AreEqual(1800, b.SetStartTime(1800));
		}

		[Test()]
		public void whenBabysitterIsPassedAnEarlyStartTimeItReturnsNegativeOne ()
		{
			Assert.AreEqual (-1, b.SetStartTime(1400));
		}

		[Test()]
		public void whenBabysitterIsPassedAValidEndTimeItReturnsTheGivenTime()
		{
			Assert.AreEqual(2700, b.SetEndTime(0300));
		}

		[Test()]
		public void whenBabysitterIsPassedALateEndTimeItReturnsNegativeOne ()
		{
			Assert.AreEqual (-1, b.SetEndTime(0500));
		}

		[Test()]
		public void whenBabysitterIsPassedAValidBedtimeItReturnsTheGivenTime ()
		{
			b.SetStartTime(1800);
			b.SetEndTime(2100);
			Assert.AreEqual(2000, b.SetBedTime(2000));
		}

		[Test()]
		public void whenBabysitterIsPassedABedtimeOutsideStartTimeAndEndTimeItReturnsNegativeOne ()
		{
			b.SetStartTime(1800);
			b.SetEndTime(2000);
			Assert.AreEqual(-1, b.SetBedTime(2400));
		}

		[Test()]
		public void whenBabysitterIsPassedAnyTimeAfterMidnightItReturnsTheTimePlusTwentyFourHundred ()
		{
			Assert.AreEqual(2700, b.SetStartTime(0300));
			Assert.AreEqual(2700, b.SetEndTime(0300));
			Assert.AreEqual(2700, b.SetBedTime(0300));
		}

		[Test()]
		public void whenBabysitterIsAskedToCalculatePayItReturnsAnIntegerValueEqualToTheExpectedPay ()
		{
			b.SetStartTime(1700);
			b.SetBedTime(1800);
			b.SetEndTime(1800);
			Assert.AreEqual (12, b.CalculatePay());
		}

		[Test()]
		public void whenBabysitterIsScheduledForZeroHoursCalculatePayReturnsZero ()
		{
			b.SetStartTime(1700);
			b.SetBedTime(1700);
			b.SetEndTime(1700);
			Assert.AreEqual(0, b.CalculatePay());
		}
	}
}

